### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by aerohub** [jamiei/hexo-generator-postmap#2]
Hello, @jamiei 

I have a couple of questions:
- Is there a demo page with generated map?
- Is it possible to set more than one location for one post? If yes, how to mark it up in front matter?

Thank you

**Comment by jamiei** [comment]
Hi @aerohub,
1. There isn't currently a public one per se, but I'll DM you a link to one of my own. I will create one.
2. Unfortunately, this isn't currently supported, but I've created #3 to track this.

Thanks
